"""Initial migration with template editor tables

Revision ID: 6e9035e49614
Revises: 
Create Date: 2025-08-20 01:40:36.868320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9035e49614'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_url', sa.String(length=100), nullable=True, comment='Custom URL slug for invitation (user-defined)'))
        batch_op.add_column(sa.Column('privacy_password', sa.String(length=100), nullable=True, comment='Password protection for private invitations'))
        batch_op.add_column(sa.Column('status', sa.Enum('draft', 'published', 'archived', name='invitation_status_enum'), nullable=False, comment='Invitation status: draft, published, archived'))
        batch_op.create_unique_constraint(None, ['custom_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('status')
        batch_op.drop_column('privacy_password')
        batch_op.drop_column('custom_url')

    # ### end Alembic commands ###
