"""Add modular template support with sections_config and template_type

Revision ID: 9df20b1b5ad0
Revises: 6e9035e49614
Create Date: 2025-09-19 13:10:56.466022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df20b1b5ad0'
down_revision = '6e9035e49614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sections_config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('sections_config')
        batch_op.drop_column('template_type')

    # ### end Alembic commands ###
